Ändert aLiteral in aTerminal
hpi-swa-teaching/OhmPrettyPrint pull request #100
Opened 2020-07-30 15:41 UTC by PatriciaSowa

Closes #79

2020-07-31 12:51 UTC, Paula-Kli approved these changes

2020-08-01 08:59 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/ByteArrayLiteral.with.and.and..st
> +	resultLiterals := self value: integerTerminals.
das sollte nicht mehr resultLiterals sein

2020-08-01 09:02 UTC, T4rikA requested changes
resultLiterals in resultTerminals ändern

2020-08-01 10:02 UTC, felixauringer requested changes
siehe Discussions

2020-08-01 10:02 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/ByteArrayLiteral.with.and.and..st
> +ByteArrayLiteral: aNode with: aTerminal and: integerTerminals and: anotherTerminal
das sollte `integerLiterals` bleiben (siehe Grammatik)

2020-08-01 10:02 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/ByteArrayLiteral.with.and.and..st
> +	resultTerminal := self value: integerTerminals.
Ich faende hier `resultIntegers` recht kurz und aussagekraeftig

2020-08-01 12:44 UTC, felixauringer reviewed
Hier ist irgendwas noch ganz komisch: es gibt 20 Commits
Die Dateien, die sich geaendert haben sehen allerdings richtig aus, ich kann mir das erst Dienstag Abend angucken, aber ich denke es ist nicht so schlimm, wenn das nicht jetzt direkt gemergt wird

2020-08-03 18:05 UTC, felixauringer approved these changes

2020-08-03 18:20 UTC, felixauringer approved these changes
Ich hab die Git History repariert, meine Anmerkungen verbessert und diesen Branch auf den dev gerebased.

2020-08-03 18:58 UTC, T4rikA approved these changes

2020-08-03 18:59 UTC, merged