Kommentare anpassen und select: nutzen
hpi-swa-teaching/OhmPrettyPrint pull request #104
Opened 2020-07-30 16:28 UTC by T4rikA

In einer Methode war ein verwirrender Kommentare in einer anderen bei einem Kommentar 2 Leerzeichen zu viel.
Zudem wurde do: zu select: geändert.
closes #102

2020-07-30 17:23 UTC, Paula-Kli commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/value..st
> +	spaces := ''.
wofür brauchen wir das?

2020-07-30 17:23 UTC, Paula-Kli approved these changes

2020-07-30 19:06 UTC, PatriciaSowa approved these changes

2020-07-31 08:42 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/value..st
> +	spaces := ''.
Weil er sich sonst beschwert, dass spaces eventuell nie gesetzt wird aber gelesen

2020-08-01 09:35 UTC, felixauringer requested changes

2020-08-01 09:35 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/value..st
> +			^ spaces , result ]
newline zu viel

2020-08-01 09:38 UTC, felixauringer approved these changes

2020-08-01 09:38 UTC, merged