firstCild eingebunden
hpi-swa-teaching/OhmPrettyPrint pull request #111
Opened 2020-08-01 09:50 UTC by PatriciaSowa

closes #105

2020-08-01 11:05 UTC, felixauringer approved these changes

2020-08-02 09:09 UTC, T4rikA requested changes
Wir sollten über die 2 Kommentare reden

2020-08-02 09:09 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/FinalStatement.with.and.and..st
>  FinalStatement: aNode with: aLiteral and: aStatement and: anotherLiteral
Auch hier macht das #112 schöner

2020-08-02 09:09 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +	aBinaryMessage firstChild ifNotNil: [ result := result , ' ' , (self value: aBinaryMessage) ].
Hier macht das #112 schöner finde ich

2020-08-02 13:32 UTC, Paula-Kli commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +	aBinaryMessage firstChild ifNotNil: [ result := result , ' ' , (self value: aBinaryMessage) ].
sonst meckert zusätzlich der Linter ;)

2020-08-02 13:33 UTC, Paula-Kli approved these changes

2020-08-02 13:33 UTC, Paula-Kli commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +	aBinaryMessage firstChild ifNotNil: [ result := result , ' ' , (self value: aBinaryMessage) ].
das würde dann durch rebasen geändert werden oder?

2020-08-03 18:27 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/FinalStatement.with.and.and..st
>  FinalStatement: aNode with: aLiteral and: aStatement and: anotherLiteral
Habe das beim rebase angepasst

2020-08-03 18:29 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +	aBinaryMessage firstChild ifNotNil: [ result := result , ' ' , (self value: aBinaryMessage) ].
Durch den Rebase wird die Datei gar nicht mehr angefasst

2020-08-03 18:53 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/FinalStatement.with.and.and..st
>  FinalStatement: aNode with: aLiteral and: aStatement and: anotherLiteral
Ok gut

2020-08-03 19:00 UTC, T4rikA approved these changes

2020-08-03 19:21 UTC, merged