Baseline sollte auch updaten können
hpi-swa-teaching/OhmPrettyPrint pull request #121
Opened 2020-08-02 18:20 UTC by Paula-Kli

closes #120

2020-08-02 18:31 UTC, Paula-Kli commented
Da Squeak scheinbar keine branches mit "/" mag, hab ich das mal auf nem anderen branch ausprobiert und ich glaube, dass das gehen sollte. Dank an Ben!

2020-08-02 18:32 UTC, T4rikA requested changes

2020-08-02 18:32 UTC, T4rikA commented on packages/BaselineOfOhmPrettyPrint.package/BaselineOfOhmPrettyPrint.class/instance/projectClass.st
> +as yet unclassified
da fehlt die Kategorie

2020-08-03 17:52 UTC, felixauringer approved these changes

2020-08-03 18:41 UTC, Paula-Kli commented on packages/BaselineOfOhmPrettyPrint.package/BaselineOfOhmPrettyPrint.class/instance/projectClass.st
> +as yet unclassified
habs kategorisiert aber das ändert irgendwie hier an dem file nichts

2020-08-03 18:51 UTC, T4rikA approved these changes

2020-08-03 19:27 UTC, felixauringer approved these changes

2020-08-04 05:03 UTC, PatriciaSowa approved these changes

2020-08-04 05:03 UTC, merged