Leerzeichen und Zeilenumbrüche in Message Sends
hpi-swa-teaching/OhmPrettyPrint pull request #21
Opened 2020-05-31 17:41 UTC by felixauringer

closes #20 
closes #18 

Weil wir die Methode für den Keyword-Knoten sowieso bearbeitet haben, haben wir direkt Leerzeichen und Zeilenumbrüche eingefügt.

2020-05-31 18:26 UTC, PatriciaSowa approved these changes

2020-05-31 18:37 UTC, PatriciaSowa approved these changes

2020-05-31 19:00 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +
Hier ist ne Leerzeile zu viel oder?

2020-05-31 19:02 UTC, T4rikA requested changes
@Paula-Kli meinte noch das Ohm die Leerzeichen usw. eh entfernt, also können wir es auch ordentlich im Test formatieren.

2020-05-31 19:09 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/OPEvaluator.class/class/evaluate.startingFrom..st
> +evaluate: aString startingFrom: aSymbol
wir haben im OPPrinter eine sehr ähnliche Methode geschrieben, die bisher nur evaluate: heißt, aber leicht erweiterbar ist... könnte man gut zusammenlegen

2020-05-31 19:11 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithMultipleSegments.st
> +					String tab , 'and: ' , String cr , '2'.
brauchen wir da einen Kommentar um zu verstehen, weshalb das so komisch umgebrochen ist? Um zu verstehen, dass es als Test gemeint ist?

2020-05-31 19:11 UTC, Paula-Kli approved these changes

2020-06-01 16:44 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/OPEvaluator.class/class/evaluate.startingFrom..st
> +evaluate: aString startingFrom: aSymbol
Das machen wir im Test-Refactoring

2020-06-01 17:06 UTC, T4rikA approved these changes

2020-06-01 17:07 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
> +
jup, ist weg

2020-06-01 17:07 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithMultipleSegments.st
> +					String tab , 'and: ' , String cr , '2'.
komische Umbrueche sind weg

2020-06-01 17:11 UTC, merged