Fügt Zeilenumbruch nach lokalen Variablen hinzu
hpi-swa-teaching/OhmPrettyPrint pull request #22
Opened 2020-05-31 18:09 UTC by PatriciaSowa

closes #19

2020-05-31 18:22 UTC, Paula-Kli approved these changes

2020-05-31 18:57 UTC, T4rikA commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExecutableCode.with.and.and..st
> +	^ localVariableList, (self value: moreExecutableCode)
Leerzeichen fehlt nach localVariableList

2020-05-31 18:59 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestExecutableCode.class/instance/testNewlineAfterLocalVariableList.st
> +	self assert: formatedCode equals: (evaluator value: matchResult)
Wir sollten dann mal bald alle Tests refactoren, aber erst nach dem Mergen denke ich

2020-05-31 18:59 UTC, T4rikA requested changes
Denke nur das eine Leerzeichen und den Rest danach oder was meint ihr?

2020-06-01 16:14 UTC, felixauringer approved these changes

2020-06-01 16:15 UTC, felixauringer approved these changes

2020-06-01 16:23 UTC, felixauringer approved these changes

2020-06-01 16:27 UTC, T4rikA approved these changes

2020-06-01 16:27 UTC, merged