WIP: Kaskadennachricht in neue Zeile
hpi-swa-teaching/OhmPrettyPrint pull request #32
Opened 2020-06-11 15:13 UTC by Paula-Kli

closes #30

2020-06-11 15:43 UTC, PatriciaSowa commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/CascadedMessages.with.and.and..st
> +	^ result
Hier fehlt eine Newline am Ende?

2020-06-11 15:43 UTC, PatriciaSowa commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExpressionOperandCascade.with.and..st
> +	^ result
Hier auch

2020-06-11 17:00 UTC, T4rikA approved these changes

2020-06-11 17:36 UTC, PatriciaSowa approved these changes

2020-06-13 14:23 UTC, felixauringer requested changes
Wir sollten noch irgendwo dokumentieren, dass `unaryCascade` und `binaryCascade` nicht vorkommen und deshalb bis es einen Bugreport gibt nicht beachtet werden, oder?

2020-06-13 14:23 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/CascadedMessages.with.and.and..st
> +CascadedMessages: aNode with: aMessageChain and: semicolon and: messageChains
bisher hatten wir hier immer `aLiteral` glaube ich

2020-06-13 14:23 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/CascadedMessages.with.and.and..st
> +		inject: ''
koennte man nicht hier einfach `result` injecten und braeuchte dann nicht mehr das aneinanderhaengen mit `,`?

2020-06-14 16:35 UTC, felixauringer approved these changes

2020-06-14 16:44 UTC, merged