Code Highlighting in allen Fenstern
hpi-swa-teaching/OhmPrettyPrint pull request #52
Opened 2020-06-25 19:06 UTC by T4rikA

closes #51

2020-06-28 12:59 UTC, PatriciaSowa approved these changes

2020-06-28 12:59 UTC, PatriciaSowa commented on packages/OmegaPrint-Core.package/MessageSet.extension/instance/aboutToStyle..st
> +	(#( newMessage editMessage editClass newClass ) includes: type) ifFalse: [ ^ false ].
Kommen nach den runden Klammern Leerzeichen?

2020-06-28 14:37 UTC, T4rikA commented on packages/OmegaPrint-Core.package/MessageSet.extension/instance/aboutToStyle..st
> +	(#( newMessage editMessage editClass newClass ) includes: type) ifFalse: [ ^ false ].
Ja weil es sich hier um ein Array handelt, da haben wir noch keine konkreten Vorgaben bekommen.

2020-07-02 09:32 UTC, Paula-Kli approved these changes

2020-07-02 11:47 UTC, felixauringer requested changes
siehe Test

2020-07-02 11:47 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testAboutToStyleImplemented.st
> +		assert: true
bei `assert: true` reicht es glaube ich nur ein `assert:` und nicht `assert:equals:` zu nutzen

2020-07-02 12:08 UTC, Paula-Kli approved these changes

2020-07-02 12:36 UTC, Paula-Kli approved these changes

2020-07-02 12:37 UTC, felixauringer approved these changes

2020-07-02 12:40 UTC, merged