Refactoring/53 tests
hpi-swa-teaching/OhmPrettyPrint pull request #54
Opened 2020-06-26 08:58 UTC by T4rikA

2020-06-27 08:41 UTC, Paula-Kli submitted a review, later dismissed

2020-06-28 12:57 UTC, PatriciaSowa submitted a review, later dismissed

2020-06-30 09:07 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testOmegaPrintStyleable.st
>  testOmegaPrintStyleable
ist der gleiche Test, wie testCodeHolderOmegaPrintStyleable. Ich würde testOmegaPrintStyleable rausschmeißen

2020-06-30 09:12 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testCodeHolderNotStyleable.st
> -testCodeHolderNotStyleable
Warum haben wir das gelöscht?

2020-06-30 09:12 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json
>  		"testExistenceButton" : "fau 6/7/2020 18:25",
MetaProgramming rausnehmen und statt each isKindOf: Collection lieber each isCollection nehmen

2020-07-02 12:17 UTC, felixauringer submitted a review, later dismissed
viel zu tun wir noch haben

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestMoreExecutableCode.class/instance/testWithMultipleStatementsWithFinalStatement.st
> +		evaluate: '2+3. 2+3. ^2+3'
Ihr habt ja ueberall Leerzeichen entfernt, muessten die hier dann nicht auch weg?

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testFormatString.st
> -		ultimateSourceCodeAt: #exampleMethod
Brauchen wir dann noch die `exampleMethod`?

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testOmegaPrintStringNegative.st
> +	self assert: '<no>omegaPrint' equals: codeHolder omegaPrintString
Einrückung

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testOmegaPrintStringPositive.st
> +	self assert: '<yes>omegaPrint' equals: codeHolder omegaPrintString
Einrückung

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json.orig
> +{
die Datei sollte nicht comitted werden

2020-07-02 12:17 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestMoreExecutableCode.class/instance/testWithMultipleStatementsWithFinalStatement.st
> +testWithMultipleStatementsWithFinalStatement
Dieser und die anderen 5 Tests basieren sehr stark auf dem Statements-Knoten, diese Logik sollte man hier vielleicht rausziehen.

2020-07-02 12:18 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json.orig
> +{
geht mit Sicherheit auf mein Konto ^^

2020-07-03 10:16 UTC, felixauringer commented
@T4rikA und ich haben ein Konzept erarbeitet, wie wir die Code Duplication in unseren Tests entfernen koennen. Das haben wir mal auf eine Testklasse angewandt und auf den Tests-Refactoring-Branch gepusht. Dort sieht man dann in den changed Files neue Dateien und Dateien, die mit 'changed since last view' gekennzeichnet sind. Schaut gerne mal drüber @Paula-Kli, @PatriciaSowa und sagt, was ihr davon haltet, bevor wir das auf alle Tests ausrollen. Wir sparen damit pro Test 4 Zeilen, was mit 70 Tests auf 280 Zeilen hinausläuft, da wir aber ein paar andere Methoden brauchen, schaetzen wir, dass wir am Ende 'nur' 200 Zeilen weniger haben.

2020-07-05 13:58 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testFormatString.st
> -		ultimateSourceCodeAt: #exampleMethod
ja um zu testen, wie es ist, wenn der Button "gedrückt" wurde

2020-07-05 14:01 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testFormatString.st
> -		ultimateSourceCodeAt: #exampleMethod
wir brauchen die Methode aber für testFormatStringWithButton

2020-07-05 14:03 UTC, Paula-Kli reviewed
Finde ich gut, was ihr gemacht habt auch mit dem prettify:equals: finde auch das der Name ganz in Ordnung ist

2020-07-07 09:26 UTC, PatriciaSowa commented on packages/OmegaPrint-Tests.package/TestBinaryMessageSend.class/instance/testWithReceiverWithMessage.st
> +
hier ist eine Leerzeile zu viel

2020-07-07 09:29 UTC, PatriciaSowa commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithLocalVariablesWithMultipleLines.st
> +		prettify: '[:arg||variable|test1.test2.]'
kommt hier ein Punkt ans Ende?

2020-07-07 09:38 UTC, Paula-Kli approved these changes

2020-07-07 09:53 UTC, PatriciaSowa approved these changes

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/instance/prettify.shouldEqual..st
> +
empty line

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestBinaryMessageSend.class/instance/testWithReceiverWithMessage.st
> +
empty line

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestBinaryMethodHeader.class/instance/testWithSelectorWithIdentifier.st
> +		shouldEqual: '@ aNumber'
inconsistent naming, sometimes 2 sometimes aNumber

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithoutLocalVariablesWithMultipleLines.st
why with argument**s**?

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithoutLocalVariablesWithSingleLine.st
why argument**s**?

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithReceiverWithMultipleSegments.st
> +		prettify: 'self test: #statement with:1 and:2'
unnecessary spaces

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestNestedExpression.class/instance/testWithStatementWithMultipleParentheses.st
> +		prettify: '((2+3))'
Dot missing

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestNestedExpression.class/instance/testWithStatementWithSingleParentheses.st
> +		prettify: '(2+3)'
Dot missing

2020-07-07 09:55 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testFormatStringWithButton.st
> +		assert: result
change assert: equals:

2020-07-07 10:12 UTC, Paula-Kli approved these changes

2020-07-07 10:20 UTC, felixauringer requested changes
Viel zu grosse Aenderungen, sollten wir nicht nochmal machen :D

2020-07-07 10:20 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/instance/prettify.shouldEqual..st
> +
newline zu viel

2020-07-07 10:20 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/properties.json
> +	"name" : "OPTestEvaluator",
was ist hier denn passiert?

2020-07-07 10:20 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithLocalVariablesWithMultipleLines.st
> +		prettify: '[:arg||variable|test1.test2.]'
Ich wuerde den da lassen, weil dann der FinalStatement Knoten nicht betroffen ist, sondern nur der Statements Knoten

2020-07-07 10:20 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestComment.class/instance/startSymbol.st
> +	^ #MethodDeclaration
Das ist ja irgendwie n bisschen komisch, dass Kommentare immer von der MethodDeclaration starten

2020-07-07 10:20 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithReceiverWithMultipleSegments.st
> +		shouldEqual: 'self' , String cr , String tab , 'test: #statement' , String cr , String tab , 'with: 1' , String cr , String tab , 'and: 2'
ist hier die newline richtig, bei mir sieht das irgendwie komisch aus

2020-07-07 10:40 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestMoreExecutableCode.class/instance/testWithMultipleStatementsWithFinalStatement.st
> +		evaluate: '2+3. 2+3. ^2+3'
verschieben wir auf einen anderen PR

2020-07-07 11:00 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/properties.json
> +	"name" : "OPTestEvaluator",
Also die Klasse ist wirklich mit allen Methoden rausgeflogen, war das so gewollt?

2020-07-07 11:07 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/properties.json
> +	"name" : "OPTestEvaluator",
Ich glaube in dem Schritt wurde nur eine neue erstellt, da wir aber MethodHeader noch aufgeteilt haben in unary, binary und keyword (damit wir immer ein symbol haben), gibt es diese Klasse nicht mehr. Kann mich gerne jemand berichtigen

2020-07-07 11:47 UTC, Paula-Kli commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/properties.json
> +	"name" : "OPTestEvaluator",
TestMethodHeader ist außerdem auch komplett rausgeflogen, da wir das in TestBinaryMethodHeader, TestUnaryMethodHeader usw aufgeteilt haben
Dennoch ist glaube hier nur die Klasse genutzt worden

2020-07-07 12:08 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/OPTestEvaluator.class/properties.json
> +	"name" : "OPTestEvaluator",
Ok, das die Klasse mitsamt Methoden rausgeflogen ist, weil das in andere Klassen aufgeteilt wurde, reicht mir :+1:

2020-07-07 12:09 UTC, felixauringer approved these changes
Die letzten paar unresolved discussions muessen wir dann noch in ein weiteres Issue auslagern

2020-07-07 12:19 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithoutLocalVariablesWithMultipleLines.st
siehe im neuen Issue #66

2020-07-07 12:19 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithArgumentsWithoutLocalVariablesWithSingleLine.st
siehe im neuen Issue #66

2020-07-07 12:24 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestMoreExecutableCode.class/instance/testWithMultipleStatementsWithFinalStatement.st
> +		evaluate: '2+3. 2+3. ^2+3'
siehe #67

2020-07-07 12:27 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestBinaryMethodHeader.class/instance/testWithSelectorWithIdentifier.st
> +		shouldEqual: '@ aNumber'
siehe #67

2020-07-07 12:27 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithReceiverWithMultipleSegments.st
> +		prettify: 'self test: #statement with:1 and:2'
siehe #67

2020-07-07 12:28 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestNestedExpression.class/instance/testWithStatementWithMultipleParentheses.st
> +		prettify: '((2+3))'
siehe #67

2020-07-07 12:28 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestNestedExpression.class/instance/testWithStatementWithSingleParentheses.st
> +		prettify: '(2+3)'
siehe #67

2020-07-07 12:37 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/instance/testFormatStringWithButton.st
> +		assert: result
siehe #68

2020-07-07 12:48 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestComment.class/instance/startSymbol.st
> +	^ #MethodDeclaration
siehe [diesen Kommentar](https://github.com/hpi-swa-teaching/OhmPrettyPrint/pull/69#issuecomment-654833306)

2020-07-07 12:50 UTC, felixauringer commented
Wie man im Verlauf dieser PR sehen kann, habe ich die letzten unresolved discussions in die Issues #66, #67, #68 und die PR #69 ausgelagert, um diese PR nicht noch mehr aufzublasen.

2020-07-09 15:10 UTC, felixauringer approved these changes

2020-07-09 15:19 UTC, felixauringer approved these changes

2020-07-09 15:24 UTC, merged