Refactoring of rule methods
hpi-swa-teaching/OhmPrettyPrint pull request #63
Opened 2020-07-05 16:53 UTC by Paula-Kli

closing #62

2020-07-05 18:27 UTC, PatriciaSowa approved these changes

2020-07-05 19:59 UTC, T4rikA approved these changes

2020-07-07 09:31 UTC, felixauringer requested changes
Nur eine Anmerkung :tada:

2020-07-07 09:31 UTC, felixauringer commented on packages/OmegaPrint-Core.package/OPPrinter.class/instance/KeywordMessageSend.with.and..st
> +	keywordMessageSegments children do: [ :segment | result := result , (self newline) , (self value: segment) ].
Ich wuerde denken, dass `self newline` keine Klammern braucht, weil die Praezendenz von UnaryMessages hoeher ist als die von BinaryMessages.

2020-07-07 09:57 UTC, T4rikA approved these changes

2020-07-07 10:32 UTC, felixauringer approved these changes

2020-07-07 10:37 UTC, merged