Use consistent input strings in tests
hpi-swa-teaching/OhmPrettyPrint pull request #71
Opened 2020-07-10 09:37 UTC by felixauringer

Closes #67

2020-07-10 09:48 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestKeywordMethodHeader.class/instance/testWithMultipleSegments.st
> +		prettify: 'message1:arg1 message2:arg2'
Sollten wir hier eine andere Benennung waehlen, weils ein Header ist?

2020-07-10 09:51 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json
> -		"testToggleOmegaPrint" : " 7/9/2020 17:08:30" } }
Da fehlt ja irgendwie ein Autor :D

2020-07-10 10:21 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestKeywordMethodHeader.class/instance/testWithMultipleSegments.st
> +		prettify: 'message1:arg1 message2:arg2'
Das wäre glaube recht sinnvoll, man könnte keyword1: arg1 nehmen oder so?

2020-07-10 10:24 UTC, T4rikA requested changes
im Header die Benennung noch ändern, ansonsten sieht es gut aus

2020-07-10 10:34 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestKeywordMethodHeader.class/instance/testWithMultipleSegments.st
> +		prettify: 'message1:arg1 message2:arg2'
das koennten wir tatsaechlich glaube ich direkt bei allen Sachen mit Keywords machen, das klingt sinnvoll

2020-07-10 10:39 UTC, PatriciaSowa commented on packages/OmegaPrint-Tests.package/TestUnaryMessage.class/instance/testWithSelector.st
> +		prettify: 'message'
Kommt hier message oder selector hin?

2020-07-10 10:39 UTC, PatriciaSowa approved these changes

2020-07-10 10:43 UTC, felixauringer commented on packages/OmegaPrint-Tests.package/TestUnaryMessage.class/instance/testWithSelector.st
> +		prettify: 'message'
Ich finde hier tatsaechlich eher die Methode falsch benannt, aber das war ja nicht Teil dieser PR

2020-07-11 08:22 UTC, Paula-Kli approved these changes

2020-07-11 11:17 UTC, T4rikA commented on packages/OmegaPrint-Tests.package/TestUnaryMessage.class/instance/testWithSelector.st
> +		prettify: 'message'
Aber habt ihr das dann irgendwo festgehalten?
Wäre glaube auch für testWithMessage

2020-07-11 12:52 UTC, T4rikA approved these changes

2020-07-11 12:53 UTC, merged